spring.application.name=fazbear-productos
server.port=8081

# =============================================
# BASE DE DATOS H2 (Desarrollo Local / Postman)
# =============================================
spring.datasource.url=jdbc:h2:mem:productosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Carga datos iniciales
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# =============================================
# SEGURIDAD: JWT via Azure Entra ID (ACTIVO)
# Spring Boot valida firma JWKS, issuer y audience
# automaticamente. Sin token valido -> 401.
# =============================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/ee0d2c5b-e60b-4c57-9b30-8a38a520c430/v2.0
